// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE20kDQd7vahCYkHVbbd0oH8S63TFRg8Q',
    appId: '1:291998680652:web:b8b2f2d39827bffcb456e9',
    messagingSenderId: '291998680652',
    projectId: 'hotelio-ca8b7',
    authDomain: 'hotelio-ca8b7.firebaseapp.com',
    storageBucket: 'hotelio-ca8b7.appspot.com',
    measurementId: 'G-8PSCW3R90X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT496eOqGjTWqxr2bZD7_8qlucLn6HRF0',
    appId: '1:291998680652:android:3bd0e57d0b987ae5b456e9',
    messagingSenderId: '291998680652',
    projectId: 'hotelio-ca8b7',
    storageBucket: 'hotelio-ca8b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgDKIy9ct-0XJj9Pt133lOHjla9Gik-9g',
    appId: '1:291998680652:ios:b25fe01df5241f98b456e9',
    messagingSenderId: '291998680652',
    projectId: 'hotelio-ca8b7',
    storageBucket: 'hotelio-ca8b7.appspot.com',
    iosBundleId: 'com.example.hotelio',
  );
}
